### ISSUE TITLE
Website Design

### ISSUE THREAD

**Issue by PastaLaPate** [iamEvanYT/ttd-website#1]
For design 
  - hero text should not be centered it makes it harder to read
  - the icon on the top bar is not very good
  - maybe add some images with a gradient on top that goes from green to transparent
  - color theme to system by default
  - maybe make better responsive for the features thing

i can help for the bar to find units

**Comment by iamEvanYT** [comment]
1. What hero text?
2. The icon is fine.
3. What do you suggest? Use tailwind.
4. It is system preference by default.
5. features is just a preview, its fine

**Comment by PastaLaPate** [comment]
![image](https://github.com/user-attachments/assets/e34c4f94-9be2-4a72-820f-9eee3ce2972b)

**Comment by iamEvanYT** [comment]
no, that's fine.
